name: Mirror to Codeberg

on: [push, delete, create]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg Mirror
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          # Configure Codeberg authenticated URL using your secret token
          git remote add codeberg https://YuvalKolodkin:${CODEBERG_TOKEN}@codeberg.org/YuvalKolodkin/Calculab.git
          
          # Force push all branches and tags to Codeberg
          git push codeberg --prune --force --all
          git push codeberg --prune --force --tags
